public enum Nickname {
    LUMINIS,ESTRELLAALTA,CANTARIN,BOSQUEVIVO,LARGOOREJA,
    DEVORADORDEALMAS,BRAZODEHIERRO,GRUNION,PIELVERDE,CARNICERO,
    SENIORDELAGUERRA,REINADELCOMERCIO,ALTOCONSEJERO,VAGABUNDO,GUARDIANDELREINO

    }
